version: '3.8'

services:
  note-app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./notes.db:/app/notes.db
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/notes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s